version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ems_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ems_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: iloveyou044
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user -d ems_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  
