"""create db

Revision ID: a5ce4db5fb27
Revises: 
Create Date: 2025-09-11 15:30:44.877155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5ce4db5fb27'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cv',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('id_seta', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('current_position', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id_seta')
    )
    op.create_index(op.f('ix_cv_email'), 'cv', ['email'], unique=True)
    op.create_table('cv_draft',
    sa.Column('id', sa.String(length=6), nullable=False),
    sa.Column('id_seta', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=50), nullable=True),
    sa.Column('current_position', sa.String(length=255), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'APPROVED', 'REJECTED', name='draftstatusenum'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('id_seta')
    )
    op.create_index(op.f('ix_cv_draft_email'), 'cv_draft', ['email'], unique=True)
    op.create_table('language_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=6), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=True),
    sa.Column('proficiency', sa.Enum('NATIVE', 'FLUENT', 'INTERMEDIATE', 'BASIC', name='proficiencyenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('languages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.String(length=6), nullable=False),
    sa.Column('language_name', sa.String(length=100), nullable=True),
    sa.Column('proficiency', sa.Enum('NATIVE', 'FLUENT', 'INTERMEDIATE', 'BASIC', name='proficiencyenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('project_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=6), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('programming_languages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.String(length=6), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=True),
    sa.Column('project_description', sa.Text(), nullable=True),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('responsibilities', sa.Text(), nullable=True),
    sa.Column('programming_languages', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soft_skill_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=6), nullable=False),
    sa.Column('skill_name', sa.Enum('COMMUNICATION', 'TEAMWORK', 'PROBLEM_SOLVING', 'DECISION_MAKING', 'LEADERSHIP', 'TIME_MANAGEMENT', 'ADAPTABILITY', 'OTHER', name='softskillenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('soft_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.String(length=6), nullable=False),
    sa.Column('skill_name', sa.Enum('COMMUNICATION', 'TEAMWORK', 'PROBLEM_SOLVING', 'DECISION_MAKING', 'LEADERSHIP', 'TIME_MANAGEMENT', 'ADAPTABILITY', 'OTHER', name='softskillenum'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_skill_drafts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('draft_id', sa.String(length=6), nullable=False),
    sa.Column('category', sa.Enum('PROGRAMMING_LANGUAGE', 'DATABASE', 'FRAMEWORK', 'TOOL', 'HARDWARE', name='skillcategoryenum'), nullable=True),
    sa.Column('skill_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('technical_skills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cv_id', sa.String(length=6), nullable=False),
    sa.Column('category', sa.Enum('PROGRAMMING_LANGUAGE', 'DATABASE', 'FRAMEWORK', 'TOOL', 'HARDWARE', name='skillcategoryenum'), nullable=True),
    sa.Column('skill_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('technical_skills')
    op.drop_table('technical_skill_drafts')
    op.drop_table('soft_skills')
    op.drop_table('soft_skill_drafts')
    op.drop_table('projects')
    op.drop_table('project_drafts')
    op.drop_table('languages')
    op.drop_table('language_drafts')
    op.drop_index(op.f('ix_cv_draft_email'), table_name='cv_draft')
    op.drop_table('cv_draft')
    op.drop_index(op.f('ix_cv_email'), table_name='cv')
    op.drop_table('cv')
    # ### end Alembic commands ###