"""Remove employee_id column from employees table

Revision ID: remove_employee_id_001
Revises: fa56a437da83
Create Date: 2025-09-16 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'remove_employee_id_001'
down_revision: Union[str, None] = 'fa56a437da83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Remove unique constraint on employee_id first (if it exists)
    try:
        op.drop_constraint('uq_employees_employee_id', 'employees', type_='unique')
    except:
        pass  # Constraint might not exist
    
    # Drop the employee_id column
    op.drop_column('employees', 'employee_id')
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Add back the employee_id column
    op.add_column('employees', sa.Column('employee_id', sa.String(length=50), nullable=True))
    
    # Add back unique constraint
    op.create_unique_constraint('uq_employees_employee_id', 'employees', ['employee_id'])
    
    # ### end Alembic commands ###
