

"""add permission

Revision ID: 2e16b933a05c
Revises: efcaf3a368a7
Create Date: 2025-09-29 13:28:42.276512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e16b933a05c'
down_revision: Union[str, None] = 'efcaf3a368a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('employee_sessions', 'session_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=True)
    op.drop_constraint('employee_sessions_session_token_key', 'employee_sessions', type_='unique')
    op.create_index(op.f('ix_employee_sessions_session_token'), 'employee_sessions', ['session_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_sessions_session_token'), table_name='employee_sessions')
    op.create_unique_constraint('employee_sessions_session_token_key', 'employee_sessions', ['session_token'])
    op.alter_column('employee_sessions', 'session_token',
               existing_type=sa.VARCHAR(length=1024),
               nullable=False)
    # ### end Alembic commands ###
